version = 0.1
[default.deploy.parameters]
stack_name = "kb-upload"
resolve_s3 = true
s3_prefix = "kb-upload"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "SourceBucketName=\"s3-knowledge-upload\""
