AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function that validates the structure of the Chat Bot knowledge file.

Parameters:
  SourceBucketName:
    Type: String
    Default: "s3-knowledge-upload"

  OutputBucketName:
    Type: String
    Default: "s3-knowledge-staging"

Resources:
  ValidationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lib/build/distributions/lib.zip
      Handler: aws.HandleValidation
      Runtime: java17
      Description: Java function for validating the chatbot definition.
      MemorySize: 2048
      Timeout: 10
      # Function's execution role
      Policies:
        # Provides write permissions to CloudWatch Logs.
        - AWSLambdaBasicExecutionRole
        # Provides read-only access to AWS Lambda service, AWS Lambda console features, and other related AWS services.
        - AWSLambda_ReadOnlyAccess
        # Provides minimum permissions for a Lambda function to execute while accessing a resource within a VPC - create, describe, delete network interfaces and write permissions to CloudWatch Logs.
        - AWSLambdaVPCAccessExecutionRole

        - S3ReadPolicy:
             BucketName: !Ref SourceBucketName
      Tracing: PassThrough

  TransformationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/build/distributions/lib.zip
      Handler: aws.HandleTransformation
      Runtime: java17
      Description: Java function for transformation
      MemorySize: 2048
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - S3WritePolicy:
            BucketName: !Ref OutputBucketName
        - S3ReadPolicy:
            BucketName: !Ref SourceBucketName
      Tracing: PassThrough

  S3WritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: s3:PutObject
            Resource:
              Fn::Sub: arn:aws:s3:::${OutputBucketName}/*

Outputs:
  ValidationLambdaFunctionArn:
    Description: "ARN of the Validation Lambda function"
    Value: !GetAtt ValidationFunction.Arn

  TransformationLambdaFunctionArn:
    Description: "ARN of the Transformation Lambda function"
    Value: !GetAtt TransformationFunction.Arn



