/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kb_upload;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class KnowledgeTest {
    @Test void nameMissing() {

        final JSON json = new JSONData(new FileLoader("knowledge_name_missing.json").load());
        final JSONSchema jsonSchema = new JSONSchemaData(new FileLoader("knowledgeSchema.json").load());

        final Validator<JSONSchema, JSON> validator = new JSONValidator();

        final Validated validate = validator.validate(jsonSchema, json);

        assertThat(validate.state()).isInstanceOf(ValidatedStateError.class);
        assertThat(validate.messages().get(0)).isEqualTo("$.utterance[1].name: is missing but it is required");
    }

    @Test void entryMissing() {

        final JSON json = new JSONData(new FileLoader("knowledge_entry_missing.json").load());
        final JSONSchema jsonSchema = new JSONSchemaData(new FileLoader("knowledgeSchema.json").load());

        final Validator<JSONSchema, JSON> validator = new JSONValidator();

        final Validated validate = validator.validate(jsonSchema, json);

        assertThat(validate.state()).isInstanceOf(ValidatedStateError.class);
        assertThat(validate.messages().get(0)).isEqualTo("$.utterance[0].entries: is missing but it is required");
    }

    @Test void nameEntryMissing() {

        final JSON json = new JSONData(new FileLoader("knowledge_name_entry_missing.json").load());
        final JSONSchema jsonSchema = new JSONSchemaData(new FileLoader("knowledgeSchema.json").load());

        final Validator<JSONSchema, JSON> validator = new JSONValidator();

        final Validated validate = validator.validate(jsonSchema, json);

        assertThat(validate.state()).isInstanceOf(ValidatedStateError.class);
        assertThat(validate.messages().get(0)).isEqualTo("$.utterance[0].name: is missing but it is required");
        assertThat(validate.messages().get(1)).isEqualTo("$.utterance[0].entries: is missing but it is required");
    }
}
